### ISSUE TITLE
help compiling

### ISSUE THREAD

**Issue by albatros-hmd** [Wassimulator/SimplyRend#2]
Hello there, sorry for the bother.
I have trouble compiling SimplyRend, always getting errors related to the included `emaths.h`
(If I comment the included `simplyrend.h`, it compiles and executes fine)

I tried clang++ and g++ as compilers and various versions of `-std=c++xx`, the same error list happens all the time

Here is what one of the compilations commands I tried looks like
`clang++ -std=c++17 -stdlib=libc++ -g main.c  -I/usr/include/SDL2 -lSDL2 -lGL`

The error list look like this
```
In file included from main.cpp:19:
In file included from ./simplyrend.h:92:
./dependencies/emaths.h:70:16: error: expected member name or ';' after declaration specifiers
    Emaths::v2() : e{0, 0} {}
    ~~~~~~~~~~ ^
./dependencies/emaths.h:70:20: error: invalid use of non-static data member 'e'
    Emaths::v2() : e{0, 0} {}
                   ^
./dependencies/emaths.h:70:16: error: field has incomplete type 'Emaths::v2'
    Emaths::v2() : e{0, 0} {}
    		^
./dependencies/emaths.h:59:16: note: definition of 'Emaths::v2' is not complete until the closing '}'
struct Emaths::v2
		^
./dependencies/emaths.h:151:6: error: expected ';' at end of declaration list
    }
     ^
     ;
./dependencies/emaths.h:155:16: error: no matching constructor for initialization of 'Emaths::v2'
    Emaths::v2 tojesus(a.x - b.x, a.y - b.y);
    		^       ~~~~~~~~~~~~~~~~~~~~
./dependencies/emaths.h:59:16: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct Emaths::v2
		^

```

I'd guess it's probably something very basic I'm missing, like a compile flag or something.
Would you have any idea ? Or maybe could you just give me the compilation command you use on your end so I can go from there ?

**Comment by Wassimulator** [comment]
I think the reason is that you're compiling a .c file, while SimplyRend uses some C++ functionalities. I think if the main project is .cpp it should compile fine.

I'd have to check it myself but the errors seem to indicate this.

In C, as opposed to C++ you can't initialize data members of a struct in its definition, Emaths does that.

**Comment by albatros-hmd** [comment]
It seems I have the exact same errors : /
`clang++ -std=c++17 -stdlib=libc++ -g main.cpp  -Wall -Wextra -Wno-missing-braces -I/usr/include/SDL2 -lSDL2 -lGL `

That being said, I do include `glad.c` in `main.cpp`, not sure that should count though

**Comment by Wassimulator** [comment]
Wait a second are you including Emaths correctly? Adding "dependencies" to your include search path or going into SimplyRend.h and making sure that #include <emaths.h> is finding the file, you can put emaths.h in your main include folder or you might wanna change it to #include "dependencies/emaths.h" in SimplyRend.

I'd try moving dependencies into your main include folder, see if that fixes it.

**Comment by albatros-hmd** [comment]
Nice idea ! now I have a more contained problem.

Here is main.cpp
```
//one of those dependency is needed for emaths' rand() function
// #include <cstdlib>
#include <math.h>

#include "emaths.h"

int main()
{
    return 0;
}
```

and here are the tried compile commands : 
```
clang++ main.cpp
g++ main.cpp

clang++ -std=c++17 main.cpp
g++ -std=c++17 main.cpp
```


The errors stays the same
(here the start of the output of `clang++ main.cpp`)
```
In file included from main.cpp:6:
./emaths.h:70:16: error: expected member name or ';' after declaration specifiers
    Emaths::v2() : e{0, 0} {}
    ~~~~~~~~~~ ^
./emaths.h:70:20: error: invalid use of non-static data member 'e'
    Emaths::v2() : e{0, 0} {}
                   ^
./emaths.h:70:16: error: field has incomplete type 'Emaths::v2'
    Emaths::v2() : e{0, 0} {}
               ^
./emaths.h:59:16: note: definition of 'Emaths::v2' is not complete until the closing '}'
struct Emaths::v2
               ^
./emaths.h:151:6: error: expected ';' at end of declaration list
    }
     ^
     ;
./emaths.h:155:16: error: no matching constructor for initialization of 'Emaths::v2'
    Emaths::v2 tojesus(a.x - b.x, a.y - b.y);
               ^       ~~~~~~~~~~~~~~~~~~~~
./emaths.h:59:16: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct Emaths::v2
               ^
```

**Comment by Wassimulator** [comment]
The example above with including emaths compiles fine on Windows but that's with MSVC, I'll try it with clang on linux and get back to you

**Comment by albatros-hmd** [comment]
Many thanks : )
I'll continue trying in the mean time.

Just in case, it compiles just fine if I instead include the version of emath your have on it's own repository
https://github.com/Wassimulator/Emaths/blob/master/emaths.h

It's just the inclusion of the emath that is in SimplyRend that causes de issues.

**Comment by Wassimulator** [comment]
Ok that last comment pointed to the problem, the standalone version I have on its own repository is an updated version I am just now realising, it's more lines of code and those definitions were fixed, the library should run with that version, you should just use it and discard the old one it has some mistakes. I'll update the repository. sorry for this whole ordeal!

I updated `emaths.h` on both repositories to the latest version, should all work fine now, I hope!

**Comment by albatros-hmd** [comment]
Awesome !
Many thankes. I have to get back at work, but I can't wait to try it : )

**Comment by albatros-hmd** [comment]
It's done ! I have my hello rectangle displaying with SimplyRend !

![1666767540](https://user-images.githubusercontent.com/61659050/197956484-78c405c7-6bb2-4a0f-9b8d-cf07d1f0d1a2.png)


The only other friction I had, is that I had to add `#define STB_IMAGE_IMPLEMENTATION` before `#include "dependencies/stb_image.h"` on `simplyrend.h`.

Many thanks for sharing your library   : D

**Comment by Wassimulator** [comment]
That's awesome!
